# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 512)
        MainWindow.setMinimumSize(QtCore.QSize(800, 512))
        MainWindow.setMaximumSize(QtCore.QSize(800, 512))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tv = QtWidgets.QTableView(self.centralwidget)
        self.tv.setGeometry(QtCore.QRect(10, 130, 761, 351))
        self.tv.setAlternatingRowColors(True)
        self.tv.setSortingEnabled(True)
        self.tv.setWordWrap(False)
        self.tv.setObjectName("tv")
        self.tv.horizontalHeader().setDefaultSectionSize(60)
        self.txtUser = QtWidgets.QTextEdit(self.centralwidget)
        self.txtUser.setGeometry(QtCore.QRect(240, 30, 291, 21))
        self.txtUser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtUser.setObjectName("txtUser")
        self.btnGetTweets = QtWidgets.QPushButton(self.centralwidget)
        self.btnGetTweets.setGeometry(QtCore.QRect(340, 90, 101, 31))
        self.btnGetTweets.setObjectName("btnGetTweets")
        self.spinTweets = QtWidgets.QSpinBox(self.centralwidget)
        self.spinTweets.setGeometry(QtCore.QRect(430, 60, 42, 22))
        self.spinTweets.setSuffix("")
        self.spinTweets.setObjectName("spinTweets")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 60, 91, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analisis de sentimiento Twitter"))
        self.txtUser.setPlaceholderText(_translate("MainWindow", "Nombre de usuario"))
        self.btnGetTweets.setText(_translate("MainWindow", "Recoger Tweets"))
        self.label.setText(_translate("MainWindow", "Número de tweets"))
